name: stanford_local

services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXT_PUBLIC_HOST: ${NEXT_PUBLIC_HOST}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST}
      - NEXTAUTH_URL=${NEXTAUTH_URL}