// export const metadata = {
//   title: 'Hello World',
//   description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
